name: generate pacman animation

on:
  schedule:
    - cron: "0 */24 * * *" 
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate pacman-contribution-graph.svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: JaileneAndrade
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          # Aquí es donde ocurre la magia de Pacman
          config_order: pacman-contribution-graph
